/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as glihomeIndexImport } from './routes/(gli)/(home)/index'
import { Route as gligliIdGliIDrentalapprovalImport } from './routes/(gli)/(gli-id)/gli.$ID_rentalapproval'
import { Route as glicreateGLICreategliIDrentalapprovalImport } from './routes/(gli)/(createGLI)/creategli.$ID_rentalapproval'
import { Route as glibordereauxlistBordereauxBordereauxImport } from './routes/(gli)/(bordereaux)/(listBordereaux)/bordereaux'
import { Route as glibordereauxbordereauxIdBordereauxIDbordereauxImport } from './routes/(gli)/(bordereaux)/(bordereauxId)/bordereaux.$ID_bordereaux'

// Create/Update Routes

const glihomeIndexRoute = glihomeIndexImport.update({
  id: '/(gli)/(home)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const gligliIdGliIDrentalapprovalRoute =
  gligliIdGliIDrentalapprovalImport.update({
    id: '/(gli)/(gli-id)/gli/$ID_rentalapproval',
    path: '/gli/$ID_rentalapproval',
    getParentRoute: () => rootRoute,
  } as any)

const glicreateGLICreategliIDrentalapprovalRoute =
  glicreateGLICreategliIDrentalapprovalImport.update({
    id: '/(gli)/(createGLI)/creategli/$ID_rentalapproval',
    path: '/creategli/$ID_rentalapproval',
    getParentRoute: () => rootRoute,
  } as any)

const glibordereauxlistBordereauxBordereauxRoute =
  glibordereauxlistBordereauxBordereauxImport.update({
    id: '/(gli)/(bordereaux)/(listBordereaux)/bordereaux',
    path: '/bordereaux',
    getParentRoute: () => rootRoute,
  } as any)

const glibordereauxbordereauxIdBordereauxIDbordereauxRoute =
  glibordereauxbordereauxIdBordereauxIDbordereauxImport.update({
    id: '/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux',
    path: '/bordereaux/$ID_bordereaux',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(gli)/(home)/': {
      id: '/(gli)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof glihomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/(gli)/(bordereaux)/(listBordereaux)/bordereaux': {
      id: '/(gli)/(bordereaux)/(listBordereaux)/bordereaux'
      path: '/bordereaux'
      fullPath: '/bordereaux'
      preLoaderRoute: typeof glibordereauxlistBordereauxBordereauxImport
      parentRoute: typeof rootRoute
    }
    '/(gli)/(createGLI)/creategli/$ID_rentalapproval': {
      id: '/(gli)/(createGLI)/creategli/$ID_rentalapproval'
      path: '/creategli/$ID_rentalapproval'
      fullPath: '/creategli/$ID_rentalapproval'
      preLoaderRoute: typeof glicreateGLICreategliIDrentalapprovalImport
      parentRoute: typeof rootRoute
    }
    '/(gli)/(gli-id)/gli/$ID_rentalapproval': {
      id: '/(gli)/(gli-id)/gli/$ID_rentalapproval'
      path: '/gli/$ID_rentalapproval'
      fullPath: '/gli/$ID_rentalapproval'
      preLoaderRoute: typeof gligliIdGliIDrentalapprovalImport
      parentRoute: typeof rootRoute
    }
    '/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux': {
      id: '/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux'
      path: '/bordereaux/$ID_bordereaux'
      fullPath: '/bordereaux/$ID_bordereaux'
      preLoaderRoute: typeof glibordereauxbordereauxIdBordereauxIDbordereauxImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof glihomeIndexRoute
  '/bordereaux': typeof glibordereauxlistBordereauxBordereauxRoute
  '/creategli/$ID_rentalapproval': typeof glicreateGLICreategliIDrentalapprovalRoute
  '/gli/$ID_rentalapproval': typeof gligliIdGliIDrentalapprovalRoute
  '/bordereaux/$ID_bordereaux': typeof glibordereauxbordereauxIdBordereauxIDbordereauxRoute
}

export interface FileRoutesByTo {
  '/': typeof glihomeIndexRoute
  '/bordereaux': typeof glibordereauxlistBordereauxBordereauxRoute
  '/creategli/$ID_rentalapproval': typeof glicreateGLICreategliIDrentalapprovalRoute
  '/gli/$ID_rentalapproval': typeof gligliIdGliIDrentalapprovalRoute
  '/bordereaux/$ID_bordereaux': typeof glibordereauxbordereauxIdBordereauxIDbordereauxRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(gli)/(home)/': typeof glihomeIndexRoute
  '/(gli)/(bordereaux)/(listBordereaux)/bordereaux': typeof glibordereauxlistBordereauxBordereauxRoute
  '/(gli)/(createGLI)/creategli/$ID_rentalapproval': typeof glicreateGLICreategliIDrentalapprovalRoute
  '/(gli)/(gli-id)/gli/$ID_rentalapproval': typeof gligliIdGliIDrentalapprovalRoute
  '/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux': typeof glibordereauxbordereauxIdBordereauxIDbordereauxRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bordereaux'
    | '/creategli/$ID_rentalapproval'
    | '/gli/$ID_rentalapproval'
    | '/bordereaux/$ID_bordereaux'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bordereaux'
    | '/creategli/$ID_rentalapproval'
    | '/gli/$ID_rentalapproval'
    | '/bordereaux/$ID_bordereaux'
  id:
    | '__root__'
    | '/(gli)/(home)/'
    | '/(gli)/(bordereaux)/(listBordereaux)/bordereaux'
    | '/(gli)/(createGLI)/creategli/$ID_rentalapproval'
    | '/(gli)/(gli-id)/gli/$ID_rentalapproval'
    | '/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  glihomeIndexRoute: typeof glihomeIndexRoute
  glibordereauxlistBordereauxBordereauxRoute: typeof glibordereauxlistBordereauxBordereauxRoute
  glicreateGLICreategliIDrentalapprovalRoute: typeof glicreateGLICreategliIDrentalapprovalRoute
  gligliIdGliIDrentalapprovalRoute: typeof gligliIdGliIDrentalapprovalRoute
  glibordereauxbordereauxIdBordereauxIDbordereauxRoute: typeof glibordereauxbordereauxIdBordereauxIDbordereauxRoute
}

const rootRouteChildren: RootRouteChildren = {
  glihomeIndexRoute: glihomeIndexRoute,
  glibordereauxlistBordereauxBordereauxRoute:
    glibordereauxlistBordereauxBordereauxRoute,
  glicreateGLICreategliIDrentalapprovalRoute:
    glicreateGLICreategliIDrentalapprovalRoute,
  gligliIdGliIDrentalapprovalRoute: gligliIdGliIDrentalapprovalRoute,
  glibordereauxbordereauxIdBordereauxIDbordereauxRoute:
    glibordereauxbordereauxIdBordereauxIDbordereauxRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(gli)/(home)/",
        "/(gli)/(bordereaux)/(listBordereaux)/bordereaux",
        "/(gli)/(createGLI)/creategli/$ID_rentalapproval",
        "/(gli)/(gli-id)/gli/$ID_rentalapproval",
        "/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux"
      ]
    },
    "/(gli)/(home)/": {
      "filePath": "(gli)/(home)/index.tsx"
    },
    "/(gli)/(bordereaux)/(listBordereaux)/bordereaux": {
      "filePath": "(gli)/(bordereaux)/(listBordereaux)/bordereaux.tsx"
    },
    "/(gli)/(createGLI)/creategli/$ID_rentalapproval": {
      "filePath": "(gli)/(createGLI)/creategli.$ID_rentalapproval.tsx"
    },
    "/(gli)/(gli-id)/gli/$ID_rentalapproval": {
      "filePath": "(gli)/(gli-id)/gli.$ID_rentalapproval.tsx"
    },
    "/(gli)/(bordereaux)/(bordereauxId)/bordereaux/$ID_bordereaux": {
      "filePath": "(gli)/(bordereaux)/(bordereauxId)/bordereaux.$ID_bordereaux.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
