/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GliRouteImport } from './routes/gli'
import { Route as IndexRouteImport } from './routes/index'

const GliRoute = GliRouteImport.update({
  id: '/gli',
  path: '/gli',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gli': typeof GliRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gli': typeof GliRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gli': typeof GliRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gli'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gli'
  id: '__root__' | '/' | '/gli'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GliRoute: typeof GliRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gli': {
      id: '/gli'
      path: '/gli'
      fullPath: '/gli'
      preLoaderRoute: typeof GliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GliRoute: GliRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
